from .nougat_model_base import nougatProcessor_base
from .nougat_model_small import nougatProcessor_small
from .trocr_base_handwritten import trocr_base_handwritten
from .layoutlm_document_qa import layoutlm_document_qa